global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - rules.yml
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9876

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: jmx-kafka
    static_configs:
      - targets: ['localhost:7071']
